### ISSUE TITLE
Readme incorrectly says Fastmail is blocked.

### ISSUE THREAD

**Issue by arcayneman** [veeqtoh/laravel-active-email#4]
The blocklist contains Fast-mail, with a hyphen, not Fastmail (without the hyphen). The Overview section of the Readme incorrectly says Fastmail, without a hyphen, is black listed.

**Comment by veeqtoh** [comment]
@arcayneman Good shout. Fastmail is not a disposable email address service and is added to the grey list. In strict mode, it will be blacklisted. This is now corrected in https://github.com/veeqtoh/laravel-active-email/pull/5
